# ################################################### #
# Common Configuration for Data Crawler               #
##################################################### #

# ################################################### #
# Target Marketplace that we need to crawl            #
# ################################################### #
marketplaceName: ebay

# ################################################### #
# Strategy used to crawl above mentioned marketplace  #
# ################################################### #
strategyName: robotstxt

# ################################################### #
# Processing Directory used for crawling              #
# ################################################### #
processingDir: C:\Users\AmitG\Downloads



